create table merchant_rate
(
   UUID                 VARCHAR2(32)         not null COMMENT '商户费率',
   MERCHANT_ID          VARCHAR2(32)         not null COMMENT '商户ID',
   RATE_UUID            VARCHAR2(32)         not null COMMENT '费率套餐ID',
   OUTER_RATE_CODE      VARCHAR2(32) COMMENT '外部费率编码',
   EXPIRE_TIME          DATE COMMENT '过期时间',
   CREATER              VARCHAR2(32)         not null COMMENT '创建人',
   UPDATER              VARCHAR2(32) COMMENT '修改人',
   VERSION              bigint           not null COMMENT '版本号',
   created          timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '创建时间',
   modified         timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP   COMMENT '修改时间'
) COMMENT '商户费率';

create table merchant_rate_LOG
(
   UUID                 VARCHAR2(32)         not null comment    ,
   MERCHANT_ID          VARCHAR2(32)         not null comment  '商户ID'  ,
   USER_ID              VARCHAR2(32)comment   '用户ID' ,
   RATE_UUID            VARCHAR2(32)comment  '费率套餐ID'  ,
   RATE_NAME            VARCHAR2(64)comment  '费率套餐名称'  ,
   RATE_DESC            VARCHAR2(64)comment  '费率套餐描述'  ,
   RATE_UUID_BEFORE     VARCHAR2(32)comment  '旧费率套餐ID'  ,
   RATE_NAME_BEFORE     VARCHAR2(64)comment   '旧费率套餐名称' ,
   RATE_DESC_BEFORE     VARCHAR2(64)comment '旧费率套餐描述'   ,
   OUTER_RATE_CODE      VARCHAR2(32)comment  '外部费率CODE'  ,
   CHANGE_TYPE          VARCHAR2(2)          not null comment '生效原因类型00：VIP到期，01：购买vip，02：费率恢复到初始长期，03：其他费率变化，04：装机'   ,
   CHANGE_TYPE_DESC     VARCHAR2(32)comment  '生效原因描述'  ,
   SOURCE_TYPE          varchar2(2)          not null comment     '记录来源，00装机费率，01鑫管家设置，02MPOS生效' ,
   EXPIRE_TIME          DATEcomment    ,
   CREATER              VARCHAR2(32)         not null comment  '过期时间'  ,
   UPDATER              VARCHAR2(32)comment    ,
   VERSION              NUMBER(18)           not null comment    , 
   created         timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '创建时间'comment    ,
   modified         timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP   COMMENT '修改时间'
) comment  '商户费率记录';

comment on column merchant_rate_LOG.created is
'创建时间';
comment on column merchant_rate_LOG.modified is
'修改时间';
comment on column merchant_rate_LOG.CREATER is
'创建人';
comment on column merchant_rate_LOG.UPDATER is
'修改人';
comment on column merchant_rate_LOG.VERSION is
'版本号';


DROP TABLE MER_CALL_BACK;
CREATE TABLE MER_CALL_BACK
(
  UUID            VARCHAR2(32) NOT NULL CONSTRAINT MER_CALL_BACK_PK_UUID PRIMARY KEY comment    ,
  USER_ID         VARCHAR2(30) comment    ,
  MERCHANT_ID     VARCHAR2(20) comment    ,
  BRAND_ID        VARCHAR2(32) comment    ,
  CHANNEL         VARCHAR2(32) comment    ,
  CALL_BACK_TIME  TIMESTAMP(6) DEFAULT now() NOT NULL comment    ,
  UPDATE_DATE     DATE DEFAULT now() NOT NULL comment    ,
  CREATE_DATE     DATE DEFAULT now() NOT NULL
);
COMMENT ON COLUMN MER_CALL_BACK.UUID IS '主键';
COMMENT ON COLUMN MER_CALL_BACK.USER_ID IS '盟友id';
COMMENT ON COLUMN MER_CALL_BACK.MERCHANT_ID IS '召回商户id';
COMMENT ON COLUMN MER_CALL_BACK.BRAND_ID IS '品牌id';
COMMENT ON COLUMN MER_CALL_BACK.CHANNEL IS '销售渠道';
COMMENT ON COLUMN MER_CALL_BACK.CALL_BACK_TIME IS '召回时间';
COMMENT ON TABLE  MER_CALL_BACK IS '商户召回关系记录表';

-- 预警表
DROP TABLE MER_EARLY_WARN_XLM;
CREATE TABLE MER_EARLY_WARN_XLM(
  UUID VARCHAR2(32) NOT NULL comment    ,
  MERCHANT_ID VARCHAR2(32) comment    ,
  EARLY_WARN_TYPE VARCHAR2(2) comment    ,
  HISTORY_DEAL_AMT NUMBER(13comment    ,2) comment    ,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL comment    ,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);
COMMENT ON COLUMN MER_EARLY_WARN_XLM.UUID IS '主键';
COMMENT ON COLUMN MER_EARLY_WARN_XLM.MERCHANT_ID IS '商编';
COMMENT ON COLUMN MER_EARLY_WARN_XLM.EARLY_WARN_TYPE IS '预警类型00：60天无交易01：90天无交易';
COMMENT ON COLUMN MER_EARLY_WARN_XLM.HISTORY_DEAL_AMT IS '历史总交易额';
COMMENT ON COLUMN MER_EARLY_WARN_XLM.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN MER_EARLY_WARN_XLM.UPDATE_TIME IS '修改时间';
COMMENT ON TABLE MER_EARLY_WARN_XLM IS '商户预警表';


DROP TABLE MER_EARLY_WARN_TEMP_XLM;
CREATE TABLE MER_EARLY_WARN_TEMP_XLM(
  UUID VARCHAR2(32) NOT NULL comment    ,
  MERCHANT_ID VARCHAR2(32) comment    ,
  TRANSACTION_TYPE VARCHAR2(2) comment    ,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);
COMMENT ON COLUMN MER_EARLY_WARN_TEMP_XLM.UUID IS '主键';
COMMENT ON COLUMN MER_EARLY_WARN_TEMP_XLM.MERCHANT_ID IS '商编';
COMMENT ON COLUMN MER_EARLY_WARN_TEMP_XLM.TRANSACTION_TYPE IS '类型00：60天有交易comment    ,01：90天内有交易';
COMMENT ON COLUMN MER_EARLY_WARN_TEMP_XLM.CREATE_TIME IS '创建时间';
COMMENT ON TABLE MER_EARLY_WARN_TEMP_XLM IS '商户预警临时表';

-- YLM

DROP TABLE MER_EARLY_WARN_YLM;
CREATE TABLE MER_EARLY_WARN_YLM(
  UUID VARCHAR2(32) NOT NULL comment    ,
  MERCHANT_ID VARCHAR2(32) comment    ,
  EARLY_WARN_TYPE VARCHAR2(2) comment    ,
  HISTORY_DEAL_AMT NUMBER(13comment    ,2) comment    ,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL comment    ,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);
COMMENT ON COLUMN MER_EARLY_WARN_YLM.UUID IS '主键';
COMMENT ON COLUMN MER_EARLY_WARN_YLM.MERCHANT_ID IS '商编';
COMMENT ON COLUMN MER_EARLY_WARN_YLM.EARLY_WARN_TYPE IS '预警类型00：60天无交易01：90天无交易';
COMMENT ON COLUMN MER_EARLY_WARN_YLM.HISTORY_DEAL_AMT IS '历史总交易额';
COMMENT ON COLUMN MER_EARLY_WARN_YLM.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN MER_EARLY_WARN_YLM.UPDATE_TIME IS '修改时间';
COMMENT ON TABLE MER_EARLY_WARN_YLM IS '商户预警表';


DROP TABLE MER_EARLY_WARN_TEMP_YLM;
CREATE TABLE MER_EARLY_WARN_TEMP_YLM(
  UUID VARCHAR2(32) NOT NULL comment    ,
  MERCHANT_ID VARCHAR2(32) comment    ,
  TRANSACTION_TYPE VARCHAR2(2) comment    ,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);
COMMENT ON COLUMN MER_EARLY_WARN_TEMP_YLM.UUID IS '主键';
COMMENT ON COLUMN MER_EARLY_WARN_TEMP_YLM.MERCHANT_ID IS '商编';
COMMENT ON COLUMN MER_EARLY_WARN_TEMP_YLM.TRANSACTION_TYPE IS '类型00：60天有交易comment    ,01：90天内有交易';
COMMENT ON COLUMN MER_EARLY_WARN_TEMP_YLM.CREATE_TIME IS '创建时间';
COMMENT ON TABLE MER_EARLY_WARN_TEMP_YLM IS '商户预警临时表';




drop table MER_SILENCE cascade constraints;
-- 沉默商户
create table MER_SILENCE
(
    UUID                 VARCHAR2(32)         not null comment    ,
    MERCHANT_ID          VARCHAR2(32)         not null comment    ,
    created         timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '创建时间'
    constraint PK_MER_SILENCE primary key (UUID)
);
comment on table MER_SILENCE is
    '商户沉默';
comment on column MER_SILENCE.MERCHANT_ID is
    '商户ID';
comment on column MER_SILENCE.created is
    '创建时间';


CREATE TABLE MER_UNBIND_LOG (
  UUID VARCHAR2(32 BYTE) NOT null comment    ,
  MERCHANT_ID VARCHAR2(32 BYTE) NOT NULL comment    ,
  FACT_SN VARCHAR2(32 BYTE) comment    ,
  FACT_ID VARCHAR2(16 BYTE) comment    ,
  USER_ID VARCHAR2(32 BYTE) comment    ,
  REASON_TYPE VARCHAR2(2 BYTE) comment    ,
  REASON_REMARK VARCHAR2(128 BYTE) comment    ,
  created DATE DEFAULT now()  NOT NULL comment    ,
  modified DATE DEFAULT now() comment    ,
  CREATER VARCHAR2(32 BYTE) NOT NULL comment    ,
  UPDATER VARCHAR2(32 BYTE) comment    ,
  VERSION NUMBER(18) NOT NULL
) ;
COMMENT ON COLUMN MER_UNBIND_LOG.MERCHANT_ID IS '商户ID';
COMMENT ON COLUMN MER_UNBIND_LOG.FACT_SN IS '机具序列号';
COMMENT ON COLUMN MER_UNBIND_LOG.FACT_ID IS '厂商ID';
COMMENT ON COLUMN MER_UNBIND_LOG.USER_ID IS '归属用户ID';
COMMENT ON COLUMN MER_UNBIND_LOG.REASON_TYPE IS '解绑原因类型 01沉默再拓展自动解绑，02鑫管家主动解绑';
COMMENT ON COLUMN MER_UNBIND_LOG.REASON_REMARK IS '解绑原因描述';
COMMENT ON COLUMN MER_UNBIND_LOG.created IS '创建时间';
COMMENT ON COLUMN MER_UNBIND_LOG.modified IS '修改时间';
COMMENT ON COLUMN MER_UNBIND_LOG.CREATER IS '创建人';
COMMENT ON COLUMN MER_UNBIND_LOG.UPDATER IS '修改人';
COMMENT ON COLUMN MER_UNBIND_LOG.VERSION IS '版本号';
COMMENT ON TABLE MER_UNBIND_LOG IS '商户解绑记录';
ALTER TABLE MER_UNBIND_LOG ADD CONSTRAINT PK_MER_UNBIND_LOG PRIMARY KEY (UUID) USING INDEX ;

CREATE TABLE MER_MQ_ERROR (
  UUID VARCHAR2(32 BYTE) NOT NULL comment    ,
  ORDER_NO VARCHAR2(32 BYTE) comment    ,
  MSG VARCHAR2(4000 BYTE) comment    ,
  ERROR_INFO VARCHAR2(4000 BYTE) comment    ,
  STATUS VARCHAR2(1 BYTE) DEFAULT '0' comment    ,
  SYS_ID VARCHAR2(50 BYTE) DEFAULT NULL comment    ,
  CREATE_TIME TIMESTAMP(6) DEFAULT systimestamp comment    ,
  UPDATE_TIME TIMESTAMP(6)
);
COMMENT ON COLUMN MER_MQ_ERROR.UUID IS 'UUID';
COMMENT ON COLUMN MER_MQ_ERROR.ORDER_NO IS '交易流水号';
COMMENT ON COLUMN MER_MQ_ERROR.MSG IS 'mq消息';
COMMENT ON COLUMN MER_MQ_ERROR.ERROR_INFO IS '错误信息';
COMMENT ON COLUMN MER_MQ_ERROR.STATUS IS '状态（0：未处理，1：已处>理）';
COMMENT ON COLUMN MER_MQ_ERROR.SYS_ID IS '系统ID';
COMMENT ON COLUMN MER_MQ_ERROR.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN MER_MQ_ERROR.UPDATE_TIME IS '修改时间';
COMMENT ON TABLE MER_MQ_ERROR IS 'mq处理错误信息表';
CREATE INDEX MER_MQ_ERROR_IX ON MER_MQ_ERROR (ORDER_NO) ;

DROP TABLE OUT_FACT ;
CREATE TABLE OUT_FACT
(
  UUID VARCHAR2(32) NOT NULL CONSTRAINT OUT_FACT_PK_UUID PRIMARY KEYcomment    ,
  OUT_FACT_ID VARCHAR2(64) NOT NULL comment    ,
  MERCHANT_ID VARCHAR2(64) NOT NULL comment    ,
  BRAND_ID VARCHAR2(32) NOT NULL comment    ,
  CHANNEL VARCHAR2(32) NOT NULL comment    ,
  REMARK VARCHAR2(200) comment    ,
  created  DATE DEFAULT now() NOT null comment    ,
  UPDATE_DATE  DATE DEFAULT now() NOT NULL
);
COMMENT ON COLUMN OUT_FACT.UUID IS '主键';
COMMENT ON COLUMN OUT_FACT.OUT_FACT_ID IS '终端号';
COMMENT ON COLUMN OUT_FACT.BRAND_ID IS '产品id';
COMMENT ON COLUMN OUT_FACT.CHANNEL IS '销售渠道';
COMMENT ON COLUMN OUT_FACT.REMARK IS '备注';
COMMENT ON COLUMN OUT_FACT.created IS '创建时间';
COMMENT ON COLUMN OUT_FACT.UPDATE_DATE IS '更新时间';
COMMENT ON TABLE OUT_FACT IS '外部终端号表';
CREATE INDEX OUT_FACT_INDEX ON OUT_FACT(OUT_FACT_ID);






